Unico/Unico/Controllers/OcpController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Unico.Data.Entities;
using Unico.Data.Interfaces;
using Unico.Models;

namespace Unico.Controllers
{
    public class OcpController : Controller
    {
        public IRepository<Cartrige> CartrigesRepository { get; set; }
        public IRepository<Printer> PrintersRepository { get; set; }
        public IRepository<OcpProduct> OcpProductsRepository { get; set; }
        public IRepository<Brand> BrandsRepository { get; set; }

        // GET: /Ocp/

        public ActionResult Index()
        {
            var brands = BrandsRepository.FindAll(b => b.Name != "OCP").ToList();

           // var p = OcpProductsRepository.FindAll().ToArray();
           // var products = p.Select(prod => Mapper.Map<OcpProductModel>(prod)).ToList();

            var model = new OcpSelectModel()
                {
                    Brands = brands,
                    //OcpProducts = products
                };
            return View(model);
        }

        [HttpPost]
        public ActionResult GetPrinters(int selectedBrand)
        {
            var brand = BrandsRepository.Find(b => b.BrandId == selectedBrand);

            var printers = PrintersRepository.FindAll(p => p.Brand == brand).ToList();
           
            var json = Json(printers.Select(p=>new{PrinterId=p.PrinterId, Name=p.Name}).ToList());

            return json;
        }

        [HttpPost]
        public ActionResult GetCartriges(int selectedPrinter)
        {
            var printer = PrintersRepository.Find(b => b.PrinterId == selectedPrinter);

            var json = Json(printer.Cartriges.Select(c => new { c.CartrigeId, c.Name }).ToList());

            return json;
        }

        [HttpPost]
        public ActionResult GetPrintersByCartrige(int selectedCartrige)
        {
            var cart = CartrigesRepository.Find(b => b.CartrigeId == selectedCartrige);

            var json = Json(cart.Printers.Select(c => new { c.PrinterId, c.Name }).ToList());

            return json;
        }

        public PartialViewResult OcpProducts(int selectedPrinter, int selectedCartrige)
        {
            var ocpProducts = new List<OcpProductModel>();

            if (selectedCartrige == -1)
            {
                var printer = PrintersRepository.Find(b => b.PrinterId == selectedPrinter);

                if (printer != null && printer.Cartriges != null)
                {
                    foreach (var cartrige in printer.Cartriges)
                    {
                        var cart = CartrigesRepository.Find(b => b.CartrigeId == cartrige.CartrigeId);
                        if (cart.Products != null)
                        {
                            foreach (var p in cart.Products)
                            {
                                var ocp = OcpProductsRepository.Find(pr => pr.ExternalId == p.ExternalId);
                                if (ocp != null && ocpProducts.All(pr => pr.ExternalId != ocp.ExternalId))
                                {
                                    ocpProducts.Add(Mapper.Map<OcpProductModel>(ocp));
                                }
                            }
                        }
                    }
                }
            }
            else
            {
                var cart = CartrigesRepository.Find(b => b.CartrigeId == selectedCartrige);
                if (cart!=null & cart.Products != null)
                {
                    foreach (var p in cart.Products)
                    {
                        var ocp = OcpProductsRepository.Find(pr => pr.ExternalId == p.ExternalId);
                        if (ocp != null)
                        {
                            ocpProducts.Add(Mapper.Map<OcpProductModel>(ocp));
                        }
                    }
                }
            }

            return PartialView("OcpProducts", ocpProducts);
        }

        public PartialViewResult FrequentOcpProducts()
        {
            var p = OcpProductsRepository.FindAll().ToArray();
            var products = p.Select(prod => Mapper.Map<OcpProductModel>(prod));
            return PartialView("OcpProducts", products);
        }
    }
}

Unico/Unico/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Unico.Data.Entities;
using Unico.Data.Interfaces;
using Unico.Models;
using Unico.Infrastructure;
using Unico.Helpers;

namespace Unico.Controllers
{
    public class ShoppingCartController : Controller
    {
        public IRepository<Data.Entities.CartItem> CartItemsRepository { get; set; }
        public IRepository<Product> ProductsRepository { get; set; }

        //
        // GET: /ShoppingCart/
        //[ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Index(UserData userData)
        {
             return View(GetShoppingCartModel(userData));
        }

        [AllowAnonymous]
        public PartialViewResult ShoppingCartWidget(UserData userData)
        {
            var model = new ShoppingCartWidgetModel();
            if (null != userData)
            {
                var shoppingCartId = Session.GetShoppingCardId();
                var itemsCount = CartItemsRepository.FindAll(cart => cart.OrderId == shoppingCartId).Count();
                model.Count = itemsCount;
            }

            return PartialView("ShoppingCartWidget", model);
        }

        [HttpPost]
        [AjaxAuthorize]
        public PartialViewResult AddProduct(Guid productId, int count, UserData userData)
        {
            var shoppingCartId = Session.GetShoppingCardId();
            var cartItem = CartItemsRepository.Find(c => c.OrderId == shoppingCartId && c.ProductId == productId);
            if (cartItem == null)
            {
                cartItem = new Unico.Data.Entities.CartItem() { OrderId = shoppingCartId, ProductId = productId };
            }
            cartItem.Count += count;
            CartItemsRepository.SaveOrUpdateAll(cartItem);
            return ShoppingCartWidget(userData);
        }

        [AjaxAuthorize]
        public PartialViewResult SetCount(Guid productId, int count, UserData userData)
        {
            if (count == 0)
            {
                return DeleteItem(productId, userData);
            }
            var shoppingCartId = Session.GetShoppingCardId();
            var cartItem = CartItemsRepository.Find(c => c.OrderId == shoppingCartId && c.ProductId == productId);
            if (cartItem != null)
            {
                cartItem.Count = count;
                CartItemsRepository.SaveOrUpdateAll(cartItem);
            }
            return PartialView("ShoppingCartTable", GetShoppingCartModel(userData));
        }

        [AjaxAuthorize]
        public PartialViewResult DeleteItem(Guid productId, UserData userData)
        {
            var shoppingCartId = Session.GetShoppingCardId();
            var cartItem = CartItemsRepository.Find(c => c.OrderId == shoppingCartId && c.ProductId == productId);
            if (cartItem != null)
            {                
                CartItemsRepository.Delete(cartItem);
            }
            return PartialView("ShoppingCartTable", GetShoppingCartModel(userData));
        }

        private ShoppingCartModel GetShoppingCartModel(UserData userData)
        {

            var shoppingCartId = Session.GetShoppingCardId();
            var items = CartItemsRepository.FindAll(cart => cart.OrderId == shoppingCartId);

            return new ShoppingCartModel()
            {
                CartItems = items.Select(item =>
                {
                    var product = ProductsRepository.Find(p => p.ExternalId == item.ProductId);
                    return new Unico.Models.CartItem()
                    {
                        ProductId = product.ExternalId,
                        Brand = product.Brand.Name,
                        Count = item.Count,
                        Description = product.Description,
                        Name = product.Name,
                        Price = product.Price
                    };
                }).ToList()
            };
        }


    }
}

Unico/Unico/Views/Ocp/Index.cshtml
@model Unico.Models.OcpSelectModel

@{
    ViewBag.Title = "Подбор чернил для струйных принтеров";
}

<h1>Подбор чернил для струйных принтеров</h1>
<br/>
<table>
    <tr>
        <td valign="top" style="width:250px">
            @Html.Label("Бренд", new{style="font-size:1.2em"}) <br/>
            @Html.DropDownListFor(x => x.SelectedBrand,new SelectList(Model.Brands, "BrandId", "Name"),
                 "Выберите Бренд", new {id="brandSelect", style="width:240px"})

            <div id="printerdiv">
                @Html.Label("Принтер", new{style="font-size:1.2em"})<br/>
                <select id="printerSelect" disabled style="width:240px">
                    <option value="">Выберите принтер</option>
                </select>
            </div>

            <div id="cartrigediv">
                @Html.Label("Картридж", new{style="font-size:1.2em"}) <br/>
                <select id="cartrigeSelect" disabled style="width:240px">
                    <option value="">Выберите картридж</option>
                </select>
            </div>
        </td>
        <td valign="top">
            <div id="ocpTable">
            </div>
        </td>
    </tr>
</table>

<script type="text/javascript">
    $(document).ready(function () {
        var opts = {
            lines: 12, // The number of lines to draw
            length: 7, // The length of each line
            width: 3, // The line thickness
            radius: 10, // The radius of the inner circle
            corners: 1, // Corner roundness (0..1)
            rotate: 0, // The rotation offset
            direction: 1, // 1: clockwise, -1: counterclockwise
            color: '#000', // #rgb or #rrggbb or array of colors
            speed: 1, // Rounds per second
            trail: 60, // Afterglow percentage
            shadow: false, // Whether to render a shadow
            hwaccel: false, // Whether to use hardware acceleration
            className: 'spinner', // The CSS class to assign to the spinner
            zIndex: 2e9, // The z-index (defaults to 2000000000)
            top: 'auto', // Top position relative to parent in px
            left: 'auto' // Left position relative to parent in px
        };

        $("<div id=\"spinnerDiv\"/>").appendTo("#ocpTable");
        var target = document.getElementById("spinnerDiv");
        var spinner = new Spinner(opts).spin(target);
               
        var brand = readCookie("selected-brand");
        if (brand) {
            $("#brandSelect [value='" + brand + "']").attr("selected", "selected");
            $("#brandSelect").trigger("change");
        }
        var printer = readCookie("selected-printer")
        if (!printer)
        {
            $("#ocpTable").load('@Url.Action("FrequentOcpProducts", "Ocp")')
        }
    });
</script>

<script type="text/javascript">
    $('#brandSelect').change(function () {
        var selectedValue = $(this).val();
        createCookie("selected-brand", selectedValue, 0.01);

        $.post('@Url.Action("GetPrinters", "Ocp")', { selectedBrand: selectedValue },
            function (data) {
                var printersOptions = "<option value=\"\">Выберите принтер</option>";
                for (var i = 0; i < data.length; i++) {
                    printersOptions += "<option value='" + data[i].PrinterId + "'>" + data[i].Name + "</option>";
                }
                $("#printerSelect").find('option').remove().end().append($(printersOptions));
                $("#printerSelect").removeAttr('disabled');
                var printer = readCookie("selected-printer");
                if (printer) {
                    $("#printerSelect [value='" + printer + "']").attr("selected", "selected");
                    $("#printerSelect").trigger("change");
                }
            });
    });
</script>

<script type="text/javascript">
    $('#printerSelect').change(function () {
        var selectedValue = $(this).val();
        createCookie("selected-printer", selectedValue, 0.01);

        var cartrige = readCookie("selected-cartrige");

        $.post('@Url.Action("GetCartriges", "Ocp")', { selectedPrinter: selectedValue },
            function (data) {
                var printersOptions = "<option value=\"-1\">Все картриджи</option>";
                for (var i = 0; i < data.length; i++) {
                    printersOptions += "<option value='" + data[i].CartrigeId + "'>" + data[i].Name + "</option>";
                }
                $("#cartrigeSelect").find('option').remove().end().append($(printersOptions));
                $("#cartrigeSelect").removeAttr('disabled');
                
                if (cartrige) {
                    $("#cartrigeSelect [value='" + cartrige + "']").attr("selected", "selected");
                    $("#cartrigeSelect").trigger("change");
                }
            });

        if (!cartrige) {
            $("#ocpTable").load('@Url.Action("OcpProducts", "Ocp")' + '?selectedPrinter=' + selectedValue + '&selectedCartrige=-1')
        }
    });
</script>

<script type="text/javascript">
    $('#cartrigeSelect').change(function () {
        var selectedValue = $(this).val();
        createCookie("selected-cartrige", selectedValue, 0.01);
        var selectedPrinter = $('#printerSelect').val();
        $("#ocpTable").load('@Url.Action("OcpProducts", "Ocp")' + '?selectedCartrige=' + selectedValue + '&selectedPrinter=' + selectedPrinter)
    });
</script>

Unico/Unico/Views/Ocp/OcpProducts.cshtml
@model IEnumerable<Unico.Models.OcpProductModel>
<div id="ocpTable">
    <table id="category-table">
        <tr>
             <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Key)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Color)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cartridge)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th></th>
        </tr>
        @{
            int i = 0;
        }
        @foreach (var item in Model) {
            if (i%2 == 0)
            {
                @:<tr>            
            }
            else
            {
                @:<tr class="category-table-row-odd">
            }
            i++;
            <td>
                    <img src="@Url.Content("~"+item.Image)" alt="@item.Name" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Key)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Color)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Weight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cartridge)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @using (Ajax.BeginForm("AddProduct", "ShoppingCart", new AjaxOptions
                        {
                            UpdateTargetId = "shopingCart",
                            InsertionMode = System.Web.Mvc.Ajax.InsertionMode.Replace,
                            HttpMethod = "Post"
                        }))
                    {
                        <input type="hidden" name="count" value="1" />
                        <input type="hidden" name="productId" value="@item.ExternalId" />
                        <input type="submit" value="В корзину"/>
                    }
                </td>
            @:</tr>
        }

    </table>
</div>

Unico/Unico/Views/Ocp/OcpSelectPartial.cshtml
@model Unico.Models.OcpSelectModel

@Html.DropDownListFor(x => x.SelectedBrand,new SelectList(Model.Brands, "BrandId", "Name"),
"Выберите Бренд", new {id="brandSelect", data_url=Url.Action("GetPrinters", "Ocp")})