Unico/Unico/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Unico.Data.Entities;
using Unico.Data.Interfaces;
using Unico.Infrastructure;

namespace Unico.Controllers
{
    public class CategoryController : Controller
    {
        public IRepository<Category> CategoryRepository { get; set; }
        public IRepository<CartItem> CartItemsRepository { get; set; }

        public ActionResult Show(int categoryId)
        {
            var cat = CategoryRepository.Find(c => c.CategoryId == categoryId);
            if (cat != null)
            {
                return View(cat);
            }

            return RedirectToAction("Index", "Home");
        }

    }
}

Unico/Unico/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Unico.Data.Entities;
using Unico.Data.Interfaces;

namespace Unico.Controllers
{
    public class HomeController : Controller
    {
        public IRepository<Department> DepartmentRepository { get; set; }
        public IRepository<Category> CategoriesRepository { get; set; }

        
        public ActionResult Index()
        {
            var p = Membership.Provider;
            return View();        
        }

        public ActionResult _Menu()
        {
            var departments = DepartmentRepository.FindAll();
            return PartialView(departments);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Страница описания приложения.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Страница контактов.";

            return View();
        }
    }
}

Unico/Unico/Controllers/OcpController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Unico.Data.Entities;
using Unico.Data.Interfaces;
using Unico.Models;

namespace Unico.Controllers
{
    public class OcpController : Controller
    {
        public IRepository<Cartrige> CartrigesRepository { get; set; }
        public IRepository<Printer> PrintersRepository { get; set; }
        public IRepository<OcpProduct> OcpProductsRepository { get; set; }
        public IRepository<Brand> BrandsRepository { get; set; }

        // GET: /Ocp/

        public ActionResult Index()
        {
            var brands = BrandsRepository.FindAll(b => b.Name != "OCP").ToList();

           // var p = OcpProductsRepository.FindAll().ToArray();
           // var products = p.Select(prod => Mapper.Map<OcpProductModel>(prod)).ToList();

            var model = new OcpSelectModel()
                {
                    Brands = brands,
                    //OcpProducts = products
                };
            return View(model);
        }

        [HttpPost]
        public ActionResult GetPrinters(int selectedBrand)
        {
            var brand = BrandsRepository.Find(b => b.BrandId == selectedBrand);

            var printers = PrintersRepository.FindAll(p => p.Brand == brand).ToList();
           
            var json = Json(printers.Select(p=>new{PrinterId=p.PrinterId, Name=p.Name}).ToList());

            return json;
        }

        [HttpPost]
        public ActionResult GetCartriges(int selectedPrinter)
        {
            var printer = PrintersRepository.Find(b => b.PrinterId == selectedPrinter);

            var json = Json(printer.Cartriges.Select(c => new { c.CartrigeId, c.Name }).ToList());

            return json;
        }

        [HttpPost]
        public ActionResult GetPrintersByCartrige(int selectedCartrige)
        {
            var cart = CartrigesRepository.Find(b => b.CartrigeId == selectedCartrige);

            var json = Json(cart.Printers.Select(c => new { c.PrinterId, c.Name }).ToList());

            return json;
        }

        public PartialViewResult OcpProducts(int selectedPrinter, int selectedCartrige)
        {
            var ocpProducts = new List<OcpProductModel>();

            if (selectedCartrige == -1)
            {
                var printer = PrintersRepository.Find(b => b.PrinterId == selectedPrinter);

                if (printer != null && printer.Cartriges != null)
                {
                    foreach (var cartrige in printer.Cartriges)
                    {
                        var cart = CartrigesRepository.Find(b => b.CartrigeId == cartrige.CartrigeId);
                        if (cart.Products != null)
                        {
                            foreach (var p in cart.Products)
                            {
                                var ocp = OcpProductsRepository.Find(pr => pr.ExternalId == p.ExternalId);
                                if (ocp != null && ocpProducts.All(pr => pr.ExternalId != ocp.ExternalId))
                                {
                                    ocpProducts.Add(Mapper.Map<OcpProductModel>(ocp));
                                }
                            }
                        }
                    }
                }
            }
            else
            {
                var cart = CartrigesRepository.Find(b => b.CartrigeId == selectedCartrige);
                if (cart!=null & cart.Products != null)
                {
                    foreach (var p in cart.Products)
                    {
                        var ocp = OcpProductsRepository.Find(pr => pr.ExternalId == p.ExternalId);
                        if (ocp != null)
                        {
                            ocpProducts.Add(Mapper.Map<OcpProductModel>(ocp));
                        }
                    }
                }
            }

            return PartialView("OcpProducts", ocpProducts);
        }

        public PartialViewResult FrequentOcpProducts()
        {
            var p = OcpProductsRepository.FindAll().ToArray();
            var products = p.Select(prod => Mapper.Map<OcpProductModel>(prod));
            return PartialView("OcpProducts", products);
        }
    }
}

Unico/Unico/Views/Home/About.cshtml
@{
    ViewBag.Title = "О нас";
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>

<article>
    <p>
        
    </p>
</article>

<aside>
    <h3>Заголовок боковой панели</h3>
    <p>
        В этой области можно указать дополнительные сведения.
    </p>
    <ul>
        <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
        <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
    </ul>
</aside>

Unico/Unico/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Контакты";
}

<hgroup class="title">
</hgroup>

@section Scripts {
    @Scripts.Render("https://maps.googleapis.com/maps/api/js?sensor=false")
    <script>
        function initialize() {
            var map_canvas = document.getElementById('map_canvas');
            var latlng = new google.maps.LatLng(50.911659, 34.793088);
            var map_options = {
                center: latlng,
                zoom: 17,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            }
            var map = new google.maps.Map(map_canvas, map_options)
            var myMarker2 = new google.maps.Marker({
                position: latlng,
                map: map,
                title: "ТОВ \"РУАРТ\". Продажа OCP чернил"
            });
        }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
}

<table>
    <tr>
        <td valign="top">
     <section class="contact">
    <header>
        <h3>Адрес</h3>
    </header>
    <p>
        г. Сумы, ул. Шевченко 5
    </p>
</section>

<section class="contact">
    <header>
        <h3>Телефон</h3>
    </header>
    <p>(0542) 79-38-15<br />
        (067) 230-78-36</p>
</section>

<section class="contact">
    <header>
        <h3>Адрес электронной почты</h3>
    </header>    
    <p>
        <span>unico1203@ukr.net</span>
    </p>
</section>
        </td>

        <td>
            <div id="map_canvas"></div>
        </td>
    </tr>
</table>

Unico/Unico/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная";
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <table style="width:1200px">
                <tr>
                    <td valign="top" style="width:1000px">
                        <hgroup class="title">
                            <h1>Добро пожаловать на OCP!</h1>
                        </hgroup>
                        <p><br/>
OCP является одним из ведущих производителей водорастворимых чернил для заправки картриджей для струйных принтеров.
Компания ОСР производит более 300 видов чернил. Компания не производит универсальные чернила, а только совместимые с определенной моделью принтера. 
Как только ОЕМ создают новые чернила, исследовательский отдел компании создает альтернативный вариант, готовый для продажи.
<br/>
<br/>
Другой особенностью ОСР является тот факт, что компания производит все свои чернила в Германии. Несколько лет назад компания решила создать завод в Китае, но затем отказалась от этой идеи. Почему? Компания отказалась от производства чернил в Китае по простой причине, что подобная затея заставила бы делиться с секретом бизнес процессов и формулами чернил. А это и есть самое большое богатство компании. Вместо инвестиций в создание завода в Китае, компания инвестировала средства в передовое оборудование для своего завода в Германии.
<br/>
<br/>
@Html.ActionLink("Подбор OCP чернил", "Index", "Ocp")
<br/>
@Html.ActionLink("Контакты", "Contact", "Home")
                        </p>
                    </td>
                    <td>
                        <img src="~/Content/images/cmy_inks.jpg"/>
                    </td>
                </tr>
            </table>
            
            

            
        </div>
    </section>
}

<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />

Unico/Unico/Views/Home/_Menu.cshtml
@model IEnumerable<Unico.Data.Entities.Department>

<ul id="cssmenu1">
	<li>@Html.ActionLink("Главная", "Index", "Home")</li>
    <!--@foreach (var dep in Model)
    {        
	    <li><a href="#">@dep.Name</a>
        @if (dep.Categories.Count > 0)
        {
            <ul>                           
            @foreach (var cat in dep.Categories)
            {
	            <li>@Html.ActionLink(cat.Name, "Show", "Category", new { categoryId = cat.CategoryId }, null)</li>
            }
            </ul>
        }
        </li>
    }-->
	<li>@Html.ActionLink("OCP чернила", "Index", "Ocp")</li>
	<li>@Html.ActionLink("Контакты", "Contact", "Home")</li>
</ul>